### PR TITLE
Visual enhancements

### PR DESCRIPTION
**Pull request by pawicao**
- [x] Fix font sizes in text inputs to be at least 16px
- [x] Add an auto resize option to textarea, on each newline
- [x] Fix the scrolling behaviour
  - when more messages are loaded on top, the scroll should stay at the same messages as it was, not go to the top
  - when a user is scrolled down and a new message appears, it should automatically scroll down to show the message
  - if a user is scrolled up and they send a message, it should scroll down automatically
  - if a user is scrolled up and someone sends a message, an indicator should appear in the bottom of the messages container (absoultely positioned, in the middle) - showing that there's a new message and allowing a click that will smoothly scroll down (i have an idea how it could look hehe)
- [x] fix the Gatsby video on iOS browsers by adding a poster attribute or a special query param (whatever works)

### CODE REVIEW

**Comment by pawicao** [comment]
FYI @LoniasGR

**Comment by LoniasGR** [comment]
I would also add on the list making the load older messages a little bit more UX friendly - maybe fetch the messages, but keep the position at the same place?

**Comment by pawicao** [comment]
Yess that's what I meant by: 
> when more messages are loaded on top, the scroll should stay at the same messages as it was, not go to the top

**Comment by LoniasGR** [comment]
Α didn't register that, awesome

**Comment by LoniasGR** [comment]
When having multiline messages, they were not printed correctly - the linebreaks were not rendered. I added something to fix that.

**Review by LoniasGR — APPROVED** [review]
LGTM

**Pull request merged**
